### PR TITLE
[refactor] Major app refactor

### PR DESCRIPTION
**Pull request by brcb20**
* Use of application factory
* Blueprints for routes
* Marshallow for deserializing
* Provide default configs for prod and dev using FLASK_ENV
* CRUD Mixin to work with db models directly rather than session
* Receive art route returns JSON
* Monthly submissions counted from artpieces table rather than
  using a separate table for keeping track
* ArtpieceModel uses more specialised or restrictive types
  JSON and Enum (for status)
* Threaded confirmation email
* Logging email failures to db
* Modular/hierarchical jinja templates
* Use ArtpieceModel instead of pandas library for robot script
* Overall code clean up

BUG: in robot script (see comments in file)

### CODE REVIEW

**Comment by brcb20** [comment]
@tsdobbs this is now ready to merge

**Comment by tsdobbs** [comment]
Got it. Will test and deploy this week.

**Comment by tsdobbs** [comment]
On email send failure, user is still shown a success message and told that a confirmation email with be sent even though the email is not sent. Failed send is logged correctly, but we should probably communicate to user in some way, or raise a flag for admins

**Comment by tsdobbs** [comment]
Confirmation email looks great. Issues:

- [ ] Message to users on submission should clarify that they must confirm via email for their art to be printed
- [ ] There should be a method for cleanup of unconfirmed artpieces after a set amount of time. Can do manually for now.

**Comment by brcb20** [comment]
> On email send failure, user is still shown a success message and told that a confirmation email with be sent even though the email is not sent. Failed send is logged correctly, but we should probably communicate to user in some way, or raise a flag for admins

Communicating to the user is not possible with the current setup. The emails are sent async and we do not wait to see if the email succeeded. 
Raising a flag for an admin could be done by setting up log handling with email (to admin). Although handling an email failure by sending another email might not be the best course of action. For now, maybe we can just check the db regularly, and understand under what conditions failures occur.

**Comment by tsdobbs** [comment]
Seems like an acceptable solution. We'll need to manually force an email
send when we discover the problem, I assume, then. Or we can assume guess
whether the email is legit and confirm the artpiece manually.

(FYI: Code is merged to master)

**Pull request merged**
